CREATE TABLE questions (
    id serial PRIMARY KEY,
    title text NOT NULL,
    body text NOT NULL,
    search_vector tsvector
);

CREATE INDEX idx_questions_search ON questions USING GIN(search_vector);

-- Trigger: auto-update search_vector on INSERT/UPDATE
CREATE OR REPLACE FUNCTION questions_search_trigger() RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', COALESCE(NEW.body, '')), 'B');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_questions_search
    BEFORE INSERT OR UPDATE OF title, body ON questions
    FOR EACH ROW EXECUTE FUNCTION questions_search_trigger();

-- 50 unique questions covering distinct topics.
-- Each has different content so full-text search ranking is meaningful.
INSERT INTO questions (title, body) VALUES
('How to optimize PostgreSQL query performance', 'When running complex queries with multiple joins and aggregations, performance can degrade without proper indexing. Use EXPLAIN ANALYZE to identify sequential scans and add appropriate indexes. Partial indexes help when queries filter on specific conditions. Consider materialized views for expensive aggregations that change infrequently.'),
('Understanding B-tree indexes', 'B-tree indexes are the default index type in PostgreSQL. They work well for equality and range queries on ordered data. The tree structure keeps data sorted, allowing the planner to skip scanning the full table. Multicolumn indexes should list the most selective column first.'),
('GIN indexes for full-text search', 'GIN (Generalized Inverted Index) indexes are designed for composite values like arrays, JSONB, and tsvector. They break each value into elements and index them individually. This makes containment queries fast but slows down inserts because each element must be added to the index separately.'),
('BRIN indexes for time-series data', 'BRIN (Block Range Index) indexes store summary information about ranges of physical table blocks. They are tiny compared to B-tree indexes and work best on naturally ordered data like timestamps or auto-incrementing IDs. Not suitable for randomly ordered data.'),
('Connection pooling with PgBouncer', 'PgBouncer sits between your application and PostgreSQL, reusing database connections across many clients. In transaction mode, a connection is returned to the pool after each transaction completes. This dramatically reduces the number of active PostgreSQL backends needed.'),
('PostgreSQL streaming replication', 'Streaming replication continuously ships WAL records from primary to standby servers. The standby replays these records to stay in sync. Synchronous replication guarantees zero data loss but adds network latency to every commit. Asynchronous replication is faster but risks losing recent transactions on failover.'),
('JSONB storage and indexing', 'JSONB stores JSON in a decomposed binary format that supports efficient access to nested keys. Use the -> operator to extract a JSON object and ->> to extract as text. GIN indexes with jsonb_path_ops make containment queries fast. Avoid storing large documents — normalize when possible.'),
('Full-text search with tsvector', 'PostgreSQL full-text search converts text into tsvector tokens using language-specific stemming. The GIN index on tsvector columns makes searches fast even on millions of rows. Use websearch_to_tsquery for Google-style search syntax. Weight labels (A through D) let you rank title matches higher than body matches.'),
('Schema migration strategies', 'Database migrations should be versioned, idempotent, and applied in order. Use tools like Flyway or Liquibase to track which migrations have been applied. Always test on a copy of production data first. Backwards-compatible migrations allow rolling deployments without downtime.'),
('MVCC and transaction isolation', 'Multi-Version Concurrency Control lets readers and writers operate without blocking each other. Each transaction sees a snapshot of the database at its start time. Serializable isolation catches all anomalies but may abort transactions that conflict. Read Committed is the default and sufficient for most applications.'),
('SELECT FOR UPDATE and SKIP LOCKED', 'SELECT FOR UPDATE locks rows so other transactions cannot modify them until you commit. Adding SKIP LOCKED skips rows already locked by another transaction. This combination is the foundation of PostgreSQL-based job queues — each worker grabs the next unlocked job without waiting.'),
('Scaling with read replicas', 'Read replicas distribute SELECT queries across multiple servers. The primary handles all writes and streams changes to replicas via WAL. Application code must be aware of replication lag — a write on the primary may not be visible on the replica for a few milliseconds.'),
('Tuning shared_buffers and work_mem', 'shared_buffers controls how much memory PostgreSQL uses for caching data pages. A common starting point is 25% of system RAM. work_mem limits memory per sort or hash operation — set it too high and concurrent queries can exhaust memory. Monitor cache hit ratios to gauge effectiveness.'),
('Understanding the write-ahead log', 'The WAL guarantees durability by writing changes to a sequential log before modifying data files. On crash, PostgreSQL replays the WAL to recover committed transactions. WAL archiving enables point-in-time recovery. Unlogged tables skip the WAL for speed, trading durability for performance.'),
('Table partitioning by range', 'Range partitioning splits a table into partitions based on value ranges, typically dates. Each partition is a separate physical table. The query planner prunes partitions that cannot contain matching rows. Maintenance operations like VACUUM run per-partition, keeping them fast even on large datasets.'),
('List partitioning for multi-tenant data', 'List partitioning groups rows by discrete values like tenant_id or country. Each tenant gets its own partition. This enables per-tenant backups, per-tenant vacuuming, and even moving individual tenants to different tablespaces. Partition pruning ensures queries only scan the relevant tenant.'),
('Monitoring with pg_stat_statements', 'pg_stat_statements tracks execution statistics for every distinct query. Sort by total_exec_time to find the queries consuming the most resources. Mean time reveals slow individual queries while calls count shows frequent ones. Reset statistics periodically to track trends over deployment cycles.'),
('Autovacuum tuning for large tables', 'Autovacuum reclaims dead tuples and updates planner statistics. The default settings trigger vacuum after 20% of rows are dead — on a 100M row table, that means 20M dead rows before cleanup. Lower autovacuum_vacuum_scale_factor for large tables. Monitor n_dead_tup to detect tables falling behind.'),
('Recursive CTEs for hierarchical data', 'Recursive common table expressions traverse tree structures like org charts, threaded comments, or category hierarchies. The base case selects root nodes; the recursive term joins back to find children. Add a depth column and CYCLE detection to prevent infinite loops on circular references.'),
('Row-level security with JWT claims', 'Row-level security policies filter rows based on the current user role or session variables. Combined with PostgREST, you can set request.jwt.claims to the authenticated user and write policies like: users can only SELECT their own rows. This moves authorization from application code into the database.'),
('Foreign data wrappers for CSV files', 'file_fdw lets PostgreSQL read CSV files as if they were regular tables. Create a foreign server, then define a foreign table mapping columns to CSV fields. You can JOIN foreign tables with local tables in a single query. The file must be accessible to the PostgreSQL process.'),
('postgres_fdw for cross-database queries', 'postgres_fdw connects to remote PostgreSQL servers. Define a foreign server with connection details, create a user mapping, then import foreign tables. Queries push down WHERE clauses and aggregations to the remote server to minimize data transfer. Useful for federating data across microservices.'),
('Stored procedures vs application logic', 'Moving logic into the database reduces network round trips but makes code harder to test and version control. SQL and PL/pgSQL functions are fast for data-heavy operations. Application code is better for complex business rules, external API calls, and anything that benefits from a full programming language.'),
('Backup strategies with pg_dump', 'pg_dump produces logical backups as SQL statements or custom archive format. Use pg_basebackup for physical backups suitable for setting up replicas. Combine with WAL archiving for point-in-time recovery. Always test restores — a backup you cannot restore is not a backup.'),
('Managing connection timeouts', 'Set statement_timeout to kill runaway queries before they monopolize resources. idle_in_transaction_session_timeout closes forgotten transactions that hold locks. On the application side, use exponential backoff with jitter when retrying failed connections to avoid thundering herd problems.'),
('Reading EXPLAIN ANALYZE output', 'EXPLAIN ANALYZE executes the query and shows actual versus estimated row counts at each step. Look for large discrepancies — they indicate stale statistics. Sequential scans on large tables suggest a missing index. Nested loop joins with many iterations may benefit from a hash or merge join instead.'),
('PostgreSQL advisory locks', 'Advisory locks are application-defined locks that PostgreSQL tracks but does not enforce. Use pg_advisory_lock for session-level locks or pg_advisory_xact_lock for transaction-level ones. They are perfect for coordinating distributed workers — only one worker processes a given job ID at a time.'),
('LISTEN and NOTIFY for real-time events', 'LISTEN registers interest in a notification channel. NOTIFY sends a message to all listeners on that channel. Triggers can call pg_notify to broadcast events on INSERT or UPDATE. A lightweight WebSocket bridge can forward these notifications to browser clients without polling.'),
('Implementing job queues in PostgreSQL', 'A jobs table with status, run_at, and payload columns replaces Redis-based queues. Workers claim jobs with SELECT FOR UPDATE SKIP LOCKED, process them, then mark them complete. pg_cron can schedule periodic jobs. This eliminates a separate message broker dependency.'),
('pg_cron for scheduled tasks', 'pg_cron runs SQL statements on a cron schedule inside PostgreSQL. Schedule cache cleanup, statistics refresh, or partition maintenance without external cron jobs. Jobs run as the database user and can call any function. Check cron.job_run_details for execution history and errors.'),
('Using GENERATED ALWAYS AS columns', 'Generated columns compute their value from other columns automatically. Use STORED to persist the computed value on disk. This is useful for derived fields like full_name from first and last, or a search_vector from title and body, without triggers.'),
('Window functions for analytics', 'Window functions compute values across related rows without collapsing them into groups. ROW_NUMBER assigns sequential numbers within partitions. LAG and LEAD access previous and next rows. Running totals use SUM with an ORDER BY in the window frame.'),
('Materialized views for expensive reports', 'Materialized views store the result of a query physically on disk. REFRESH MATERIALIZED VIEW recomputes them. Use CONCURRENTLY to refresh without locking readers. They are ideal for dashboards and reports where a few minutes of staleness is acceptable.'),
('UPSERT with ON CONFLICT', 'INSERT ... ON CONFLICT DO UPDATE (upsert) atomically inserts or updates a row. Specify the conflict target — usually a unique constraint. The EXCLUDED pseudo-table references the values that would have been inserted. This replaces the old INSERT-or-UPDATE pattern with a single atomic statement.'),
('Partial indexes for filtered queries', 'A partial index includes only rows matching a WHERE clause. CREATE INDEX idx ON orders(created_at) WHERE status = ''pending'' indexes only pending orders. Queries filtering on the same condition use the smaller, faster index. Combined with UNIQUE, they enforce conditional uniqueness.'),
('Expression indexes for computed lookups', 'Expression indexes index the result of a function rather than a raw column value. CREATE INDEX idx ON users(lower(email)) speeds up case-insensitive email lookups. The query must use the exact same expression to trigger the index. Useful for JSON field access, date truncation, and text normalization.'),
('PostgreSQL enums vs check constraints', 'Enum types enforce a fixed set of values at the type level. They are stored as integers internally, making comparisons fast. However, adding new values requires ALTER TYPE and cannot remove values. Check constraints are more flexible — they are just boolean expressions and easy to modify.'),
('Lateral joins for dependent subqueries', 'LATERAL lets a subquery reference columns from preceding tables in the FROM clause. This enables per-row subqueries — for example, finding the three most recent orders for each customer. Without LATERAL, you would need a correlated subquery or complex window function.'),
('Effective use of VACUUM FULL', 'VACUUM FULL rewrites the entire table to reclaim disk space, but it locks the table exclusively for the entire duration. Regular VACUUM only marks space as reusable without reclaiming it from the OS. Use pg_repack as a non-blocking alternative to VACUUM FULL for production tables.'),
('Setting up logical replication', 'Logical replication streams row-level changes between PostgreSQL instances. Unlike streaming replication, it allows selective table replication and different schemas on publisher and subscriber. Useful for zero-downtime major version upgrades and feeding data to analytics databases.'),
('PostgreSQL and Docker best practices', 'Mount the data directory as a named volume, not a bind mount, for better performance on macOS. Set shared_buffers in postgresql.conf rather than relying on defaults. Use a healthcheck with pg_isready. Pin the PostgreSQL major version in your image tag to avoid surprise upgrades.'),
('Handling NULL values correctly', 'NULL represents unknown, not zero or empty string. Any comparison with NULL returns NULL, not false — use IS NULL or IS NOT NULL. COALESCE returns the first non-null argument. In aggregations, NULL values are silently skipped. NULLS FIRST/LAST controls sort order.'),
('Efficient bulk loading with COPY', 'COPY loads data from CSV or binary format much faster than individual INSERTs. Disable indexes and constraints before loading, then rebuild them afterward. Use FREEZE to mark rows as already frozen, skipping a future vacuum cycle. For maximum speed, load into an unlogged table first.'),
('Date and time handling in PostgreSQL', 'Use timestamptz (timestamp with time zone) for all timestamps — it stores UTC internally and converts on display. The AT TIME ZONE operator converts between zones. Interval arithmetic handles DST transitions correctly. Avoid timestamp without time zone unless you have a specific reason.'),
('Array operations and indexing', 'PostgreSQL arrays support containment (@>), overlap (&&), and element access (array[1]) operators. GIN indexes speed up containment and overlap queries. Use unnest to expand arrays into rows and array_agg to collapse rows into arrays. Arrays are zero-copy within the database, making them efficient for small lists.'),
('Using EXPLAIN for query planning', 'EXPLAIN shows the query plan without executing it. EXPLAIN ANALYZE executes and shows actual timings. EXPLAIN (BUFFERS, ANALYZE) reveals cache hit ratios. Look for Seq Scan on large tables, high loop counts in Nested Loop joins, and Sort operations that exceed work_mem. The cost estimate units are arbitrary but consistent.'),
('Securing PostgreSQL connections with SSL', 'Enable SSL in postgresql.conf with ssl = on and provide server certificates. Set sslmode=verify-full in client connection strings to prevent man-in-the-middle attacks. Use pg_hba.conf to require SSL for remote connections. Certificate-based authentication can replace passwords entirely.'),
('Implementing audit logging with triggers', 'An audit table records who changed what and when. A BEFORE trigger on the target table inserts the old row into the audit table on UPDATE or DELETE. Include current_user, current_timestamp, and the operation type. Consider partitioning the audit table by month for easy archival.'),
('PostgreSQL extensions ecosystem', 'Extensions add functionality without forking PostgreSQL. PostGIS adds geospatial queries. pgvector enables similarity search on embeddings. pg_stat_statements tracks query performance. timescaledb optimizes time-series workloads. Install with CREATE EXTENSION and manage versions with ALTER EXTENSION UPDATE.'),
('Comparing PostgreSQL to MySQL', 'PostgreSQL has richer data types, better JSON support, and true serializable isolation. MySQL is often faster for simple read-heavy workloads and has broader hosting options. PostgreSQL window functions, CTEs, and lateral joins are more mature. MySQL has improved significantly with version 8 but still lacks some advanced features.'),
('Moving from MongoDB to PostgreSQL', 'JSONB columns can store document-style data with indexing support. For most applications, a hybrid approach works: relational tables for structured data, JSONB columns for flexible attributes. PostgreSQL full-text search replaces MongoDB text indexes. Aggregation pipelines translate to SQL GROUP BY and window functions.');
