services:
  postgres:
    build: .
    ports:
      - "5438:5432"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_DB_ID: ${NOTION_DB_ID}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 2s
      retries: 10

  postgrest:
    image: postgrest/postgrest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/demo
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: anon

  nginx:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgrest
